spring:
  application:
    name: eureka-server
  profiles:
    active: eureka-server1
eureka:
  server:
    enable-self-preservation: false
  client:
    fetch-registry: true
    register-with-eureka: true